spring.application.name=flash-sale-engine

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/flash_sale_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=flash_user
spring.datasource.password=flash_password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true


# Redis Connection Settings
spring.data.redis.host=localhost
spring.data.redis.port=6379

# setting timeout so our application doesn't hang if the Docker container stops.
spring.data.redis.timeout=2000